class Contact:
    def __init__(
            self,
            first_name, middle_name, last_name,
            nickname, photo,
            title, company, address,
            home_phone_num, cell_phone_num, work_phone_num, fax,
            email1, email2, email3, homepage,
            bday, bmonth, byear,
            aday, amonth, ayear,
            address2, home_phone_2, notes
    ):
        self.first_name = first_name,
        self.middle_name = middle_name,
        self.last_name = last_name,
        self.nickname = nickname,
        self.photo = photo,
        self.title = title,
        self.company = company,
        self.address = address,
        self.home_phone_num = home_phone_num,
        self.cell_phone_num = cell_phone_num,
        self.work_phone_num = work_phone_num,
        self.fax = fax,
        self.email1 = email1,
        self.email2 = email2,
        self.email3 = email3,
        self.homepage = homepage,
        self.bday = bday,
        self.bmonth = bmonth,
        self.byear = byear,
        self.aday = aday,
        self.amonth = amonth,
        self.ayear = ayear,
        self.address2 = address2,
        self.home_phone_2 = home_phone_2,
        self.notes = notes
